# Generated by Django 5.2.14 on 2026-05-10 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_tracking', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('hours_sleep', models.FloatField(default=7.0)),
                ('stress_level', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fit_daily_summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('Walking', 'Walking'), ('Running', 'Running'), ('Cycling', 'Cycling'), ('Weight Training', 'Weight Training'), ('Yoga', 'Yoga'), ('Swimming', 'Swimming'), ('Cardio', 'Cardio'), ('HIIT', 'HIIT'), ('Stretching', 'Stretching'), ('Tennis', 'Tennis')], max_length=50)),
                ('duration_minutes', models.FloatField(default=30.0)),
                ('calories_burned', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='fitness_tracking.dailysummary')),
            ],
            options={
                'db_table': 'fit_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='DailyLog',
        ),
        migrations.AddIndex(
            model_name='dailysummary',
            index=models.Index(fields=['user', 'date'], name='summary_user_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailysummary',
            unique_together={('user', 'date')},
        ),
    ]
