# Generated by Django 5.2.14 on 2026-05-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('steps', models.PositiveIntegerField(default=0)),
                ('hours_sleep', models.FloatField(default=7.0)),
                ('stress_level', models.PositiveSmallIntegerField(default=5)),
                ('activity_type', models.CharField(choices=[('Walking', 'Walking'), ('Running', 'Running'), ('Cycling', 'Cycling'), ('Weight Training', 'Weight Training'), ('Yoga', 'Yoga'), ('Swimming', 'Swimming'), ('Cardio', 'Cardio'), ('HIIT', 'HIIT'), ('Stretching', 'Stretching'), ('Tennis', 'Tennis')], max_length=50)),
                ('duration_minutes', models.FloatField(default=0.0)),
                ('calories_burned', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fit_daily_logs',
                'ordering': ['-log_date', '-created_at'],
            },
        ),
    ]
